POST http://localhost:8080/transform_badminton_court
content-type: application/json

{
   "src_points": { 
      "p13":[261,1012],
      "p10": [1629,890],
      "p8": [409,878],
      "p14": [531,1002]
    }
 }

# {
#    "src_points": { 
#       "p13":[52,921],
#       "p15": [950,918],
#       "p10": [950,806],
#       "p9": [351,798],
#       "p100":[962,805],
#       "p155": [963,918],
#       "p8": [254,796],
#       "p14": [202,913],
#       "p16": [1680,919]
#     }
#  }

# {
#    "src_points": { 
#       "p1":[595,247],
#       "p2": [1224,271],
#       "p9": [342,484],
#       "p13": [98,566]
#     }
#  }

# {
#   "src_points": [[337,471],[945,472],[1037,680],[244,679]]
# }